property:
  gpu-id: 0
  net-scale-factor: 1.0
  offsets: 103.939;116.779;123.68
  model-color-format: 1
  labelfile-path: ../tao/export/labels.txt
  model-engine-file: ../tao/export/my_model.engine
  onnx-file: ../tao/export/my_model.onnx
  infer-dims: 3;384;1248
  maintain-aspect-ratio: 0
  batch-size: 1
  ## 0=FP32, 1=INT8, 2=FP16 mode
  network-mode: 0
  num-detected-classes: 1
  interval: 0
  gie-unique-id: 1
  network-type: 0
  cluster-mode: 3
  output-blob-names: BatchedNMS
  parse-bbox-func-name: NvDsInferParseCustomBatchedNMSTLT
  custom-lib-path: ./libnvds_infercustomparser_tao.so


#people
class-attrs-0:
  #threshold: 0.5
  pre-cluster-threshold: 0.4
  #post-cluster-threshold: 0.4
  #dbscan-min-score: 0.5
  nms-iou-threshold: 0.2
  topk: 20


